dependencies:
 - smartcontractkit/chainlink-brownie-contracts@0.3.1
compiler:
  solc:
    remappings:
     - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.1'
dotenv: .env
wallets:
  primary_key: ${PRIVATE_KEY}
  secondary_key: ${SECONDARY_PRIVATE_KEY}
networks:
  default: development
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  kovan:
    eth_usd_price_feed: '0x9326BFA02ADD2366b30bacB125260Af641031331'
    verify: True    
  development:
    verify: False
  ganache-local:
    verify: False
